config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects, only: [:index, :new, :create, :show]
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :rewards do
    resources :pledges, only: [:create]
  end

  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :user
  belongs_to :reward
  has_one :project, through: :reward
  
  validate :enough_pledged

  def enough_pledged
    unless self.dollar_amount >= reward.dollar_amount
      self.errors.add(:dollar_amount, "Amount pledged must be at least $#{reward.dollar_amount}")
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :pledges, through: :rewards
  has_many :backers, through: :rewards
  accepts_nested_attributes_for :rewards
  validates_presence_of :title, :description, :goal, :start_date, :end_date

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :pledges
  has_many :backers, through: :pledges, source: :user

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 8 }, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :require_login

  def create
    @pledge = Pledge.new(pledge_params)
    @pledge.user = current_user
    @pledge.reward = Reward.find(params[:reward_id])

    if @pledge.save
      redirect_to project_url(@pledge.project), notice: "You have successfully backed #{@pledge.project.title}!"
    else
      @project = @pledge.project
      render 'projects/show'
    end
  end

  private

  def pledge_params
    params.require(:pledge).permit(:dollar_amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @projects = Project.all
    @projects = @projects.order(:end_date)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @project.rewards.build
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_url
    else
      render :new
    end
   end

  private
  def project_params
    params.require(:project).permit(:title, :description, :goal, :start_date, :end_date, :image, rewards_attributes: [:dollar_amount, :description])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
     if @user = login(params[:email], params[:password], params[:remember_me])
      redirect_back_or_to(root_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to projects_url
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunder</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Josefin+Sans:700|Libre+Baskerville" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="site-header">
      <h1 class="logo">Crowdfunder</h1>

      <nav class="site-nav">
        <% if current_user %>
          <%= link_to "Logout", :logout, method: :delete %>
        <% else %>
          <%= link_to "Register", new_user_path %> |
          <%= link_to "Login", :login %>
        <% end %>
      </nav>
    </header>

    <% flash.each do |key, message| %>
      <div class="flash-<%= key %>"><%= message %></div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer class="site-footer">
      <small>A Bitmaker assignment</small>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, html: {multipart: true}) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :goal %>
    <%= f.number_field :goal %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div>
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date %>
  </div>

  <div>
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date %>
  </div>

  <p>Rewards</p>

  <%= f.fields_for :rewards do |r| %>
    <%= render 'reward_fields', :f => r %>
  <% end %>
  </div>

  <div>
    <%= link_to_add_association 'add reward', f, :rewards %>
  </div>
  <%= f.submit %>
<% end %>

app/views/projects/_reward_fields.html.erb
<div>
  <%= f.label :dollar_amount %>
  <%= f.number_field :dollar_amount, step: 0.01 %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<%= link_to_remove_association "remove reward", f %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <article class="project">
    <%= link_to project, class: 'project-link' do %>
      <figure class="project-image">
        <% if project.image %>
          <%= image_tag project.image %>
        <% else %>
          <%= image_tag ActionController::Base.helpers.asset_path("default.jpg") %>
        <% end %>
      </figure>
      <h1 class="project-title"><%= project.title %></h1>
      <time class="project-days-left">
        <%= icon('clock-o') %>
        <%= "#{time_ago_in_words(project.end_date)} #{( project.end_date > Time.now.utc ) ? 'remaining' : 'past deadline'}" %></time>
    <% end %>
  </article>
<% end %>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><%= @project.description %></p>
<p>Goal: <%= number_to_currency(@project.goal) %></p>
<p>Fundraising starts: <%= @project.start_date.strftime("%A %b %d %Y") %></p>
<p>Deadline: <%= @project.end_date.strftime("%A %b %d %Y") %></p>

<% if @project.image.present? %>
  <%= image_tag @project.image %>
<% end %>

<h2>Rewards</h2>
<% @project.rewards.each do |reward| %> 
  <p><%= number_to_currency(reward.dollar_amount) %></p>
  <p><%= reward.description %></p>

  <%= form_for [reward, reward.pledges.new] do |f| %>
    <%= f.number_field :dollar_amount, value: reward.dollar_amount, step: 0.01 %>
    <%= f.submit "Pledge" %>
  <% end %>

<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div class="field">
    <%= check_box_tag :remember_me %><br />
    <%= label_tag :remember_me %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
     <%= f.label :first_name %><br />
     <%= f.text_field :first_name %>
  </div>

  <div class="field">
     <%= f.label :last_name %><br />
     <%= f.text_field :last_name %>
  </div>

  <div class="field">
     <%= f.label :email %><br />
     <%= f.text_field :email %>
  </div>

  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
     <%= f.submit %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up?</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>